travis:
  secure:
    BINSTAR_TOKEN: fauVauE6xRD79+OXHRNveZay8JlA9TC5QSNLDAgTV/FGlJollWhBbrHGrm4N2tLA5FFWknJpihslEGSQREbjnxwT9ddhH2UWhwbE8DURfPOpjgmBLVpeWVb3x6BCEBWh3cQRIDvCg1da/Iv4eh6sXbSxHxx5C1BCrVINUeS6SGN/vFAkB5YkYJgImTzbXPvBCvjCy+pwMsqT5BJtbArSPbVUHxYs4u9r+Vdj8wVeL71i1TuNfr5mwZlFBdZQXN9MTNMlhZUfBpgqSI0iCDP8w3vl4Y/zxYSDJDOaK8u5sNT3z/z+qU2jM1wAhoH7ZgwGPbpT07Uy1gxn8zt9gwvPdHxaruTfMYaYh997S/lgDqVVNH3Jb6q+DrdjH6tB5PaIJj3/r993RydwoEEbADCP/rB1qcobp0gsv0n7wCyBdI9D+PJTj0SSeNtGcvi/vGDOrrKt0CgN9XhDa6OGeWzUYME2tRKmuZbVzJ0+9/vwJ9vmK95uaYYNugxC62lwXQKLhakPq61N6q+sL2uU1aTH+NCwMFUApfBy2nb7LV0yftbl+pXvPEHvS2jfU2Pxo6b22SycoZzHrwQW4Y+YeLYMzwXHgqD6PXtjZB/i8zCCCczWWU2oN5Agtn5D36dTUN3/QcrnR87IPSjSRRF7G6oQl4b/2/yV9/pZLptWVr3THf8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
